#title: The 2nd Monocular Depth Estimation Challenge
#description: MDEC @ CVPR 2023

theme: jekyll-theme-cayman

markdown: kramdown

baseurl: /WACV_1

# Remove `View on GitHub` & Download buttons
show_downloads: false
#github:
#  is_project_page: false

plugins:
  - jemoji

# 尝试关闭默认反馈/维护信息
show_downloads: false
google_analytics:
